config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'consultations/index'
  get 'consultations/list'
  get 'consultations/show'
  post 'consultations/add_comment'
  post 'consultations/add_subcomment'
  get 'consultations/get_subcomments'
  get 'consultations/search'
  get 'consultations/report_post'
  get 'consultations/sitemap'

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks', registrations: 'registrations' }

   root 'consultations#index'

end

app/models/consultation.rb
# == Schema Information
#
# Table name: consultations
#
#  id                :integer          not null, primary key
#  title             :string(255)
#  content           :text
#  consultation_type :integer
#  created_at        :datetime
#  updated_at        :datetime
#  formid            :string(255)
#  end_date          :datetime
#

class Consultation < ActiveRecord::Base

  extend Enumerize

  enumerize :consultation_type, in: { :aktualne => 0, :planowane => 1, :zakonczone => 2 }

  has_many :consultation_comments
  validates :title, presence: true, uniqueness: true
  validates :consultation_type, :end_date, presence: true

  def self.search_query(query)
    where('title LIKE :query', query: "%#{query}%")
  end

  rails_admin do
    edit do
      field :title
      field :content, :ck_editor
      field :consultation_type
      field :formid
      field :end_date
    end
  end
end

app/controllers/consultations_controller.rb
class ConsultationsController < ApplicationController
  include ActionView::Helpers::DateHelper
  include ActionView::Helpers::TextHelper

  def index
    @index_page = true
  end

  def sitemap
    
  end

  # TODO : edycja i usuwanie

  def search
    search_query = params[:q]
    @consultation_type = "Wyszukiwanie tekstu: #{search_query}"
    @consultations = Consultation.search_query(search_query)
    render :list
  end

  def list
    ctype = params[:ctype]
    @consultation_type = case ctype.to_i
              when 0 then 'Aktualne konsultacje'
              when 1 then 'Planowane konsultacje'
              when 2 then 'Zakończone konsultacje'
            end
    @consultations = Consultation.where(consultation_type: ctype).order('created_at DESC')
  end

  def show
    begin
      @consultation = Consultation.find(params[:id])
      @consultations = Consultation.where(consultation_type: @consultation.consultation_type).order('created_at DESC').limit(4)
      @oldc = @consultation.consultation_comments.where(user_id: current_user.id).first if current_user
    rescue => e
      logger.error(e)
      redirect_to :action => :list, :ctype => 0
    end
  end

  def add_comment
    respond_to do |format|
      consultation = Consultation.find(params[:consultation_id])
      unless consultation
        @message = 'Zły consultation id'
        format.js do
          return render js: <<-endjs
            alert('#{@message}');
          endjs
        end
        format.html do
          return
        end
      end

      unless current_user
        @message = 'Użytkownik niezalogowany'
        format.js do
          return render js: <<-endjs
            alert('#{@message}');
          endjs
        end
        format.html do
          return
        end
      end

      oldc = consultation.consultation_comments.where(user_id: current_user.id).first
      if oldc
        @message = 'Już skomentowałeś'
        format.js do
          return render js: <<-endjs
            alert('#{@message}');
          endjs
        end
        format.html do
          return
        end
      end

      comment = ConsultationComment.new()
      comment.content = params[:consultation_comment][:content]
      comment.user = current_user

      unless comment.valid?
        @message = 'Podaj treść komentarza'
        format.js do
          return render js: <<-endjs
            alert('#{@message}');
          endjs
        end
        format.html do
          return
        end
      end

      consultation.consultation_comments << comment

      comments_count = consultation.consultation_comments.length

      @message = 'Komentarz dodany'

      format.js do
        temp = "updateComment('#{comments_count}', '#{current_user.name}', '#{time_ago_in_words(Time.now)}', '#{Rack::Utils.escape_html(comment.content).gsub(/\r/, '').gsub(/\n/, '<br>')}', '#{comment.id}');"
        render js: temp
      end
      format.html do
        return
      end
    end
  end

  def get_subcomments
    comment = ConsultationComment.find(params[:id])
    unless comment
      @message = 'Komentarz nie istnieje'
      if request.xhr?
        return render js: <<-endjs
          alert('#{@message}');
        endjs
      else
        return
      end
    end
    if request.xhr?
      render partial: 'subcomments_list', locals: { subcomments: comment.get_subcomments, comment: comment}
    else
      @subcomments = comment.get_subcomments
      @comment = comment
    end
  end

  def add_subcomment
    parentcomment = ConsultationComment.find(params[:comment_id])
    unless parentcomment
      @message = 'Zły comment id'
      return render layout: false, status: 404
    end

    unless current_user
      @message = 'Użytkownik niezalogowany'
      return render layout: false, status: 404
    end

    comment = ConsultationComment.new()
    comment.content = params[:consultation_comment][:content]
    comment.user = current_user

    unless comment.valid?
      @message = 'Podaj treść komentarza'
      return render layout: false, status: 404
    end

    comment.parent_consultation_comment_id = parentcomment.id
    comment.save!

    @message = 'Komentarz dodany'

    if request.xhr?
      render partial: 'subcomment', locals: { subcomment: comment }
    end
  end

  def report_post
    comment = ConsultationComment.find(params[:id])
    if comment
      UserMailer.report_email(comment).deliver
    end
    render :nothing => true, :status => 200, :content_type => 'text/html'
  end
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/views/consultations/_comment.html.erb
<div class="post <% if comment.user.admin %>adminPost<% end %>">
  <img src="<%= comment.user.image.present? ? comment.user.image : asset_path('post/avatar.jpg') %>" class="avatar" alt="avatar" />
  <div class="content"id="comment_<%= comment.id %>">
    <span><strong><%= comment.user.name %></strong> - <%= time_ago_in_words(comment.created_at) %> temu</span>
    <p><%= raw(h(comment.content).gsub(/\r/, '').gsub(/\n/, '<br>')) %></p>
    <%= link_to "pokaż odpowiedzi (#{comment.subcomments_count})", consultations_get_subcomments_path(id: comment.id),
                remote: true, id: "showanswers_#{comment.id}", class: 'showReplyButton replyToComment' %>
    <% unless @consultation.consultation_type == 2 %>
        <%= link_to 'odpowiedz', consultations_get_subcomments_path(id: comment.id),
                remote: true, id: "gotoreply_#{comment.id}", class: 'replyButton replyToComment instantReply' %>
        <a class="reportButton" id="reportbutton_<%= comment.id %>">zgłoś</a>
    <% end %>
  </div>
  <div class="loadingBox" style="display: none;" id="commentloadingbox_<%= comment.id %>">
    <span>trwa ładowanie komentarzy</span>
    <div class="one"></div>
    <div class="two"></div>
    <div class="three"></div>
  </div>
</div>

app/views/consultations/_subcomment.html.erb
<div class="post reply <% if subcomment.user.admin %>adminPost<% end %>">
  <img src="<%= subcomment.user.image.present? ? subcomment.user.image : asset_path('post/avatar.jpg') %>" class="avatar" alt="avatar" />
  <div class="content">
    <span><strong><%= subcomment.user.name %></strong> - <%= time_ago_in_words(subcomment.created_at) %> temu</span>
    <p><%= raw(h(subcomment.content).gsub(/\r/, '').gsub(/\n/, '<br>')) %></p>
  </div>
</div>

app/views/consultations/_subcomments_list.html.erb
<% for subcomment in subcomments %>
    <%= render partial: 'subcomment', locals: {subcomment: subcomment} %>
<% end %>
<% if user_signed_in? and comment.consultation.consultation_type != 2 %>
<div class="post reply add" id="subcommentForm_<%= comment.id.to_s %>">
  <img src="<%= current_user.image.present? ? current_user.image : asset_path('post/avatar.jpg') %>" class="avatar" alt="avatar" />
  <div class="content">
    <%= form_for :consultation_comment, remote: true, url: consultations_add_subcomment_path, :html => {:class => 'subcommentForm', :id => 'scc_' + comment.id.to_s },
                 method: 'POST' do |f| %>
        <input type="hidden" name="comment_id" value="<%= comment.id %>" />
        <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
        <%= f.text_area :content, class: 'inputPost', placeholder: 'Podziel się swoją opinią', id: "subcommentInput_#{comment.id}", maxlength: 5000 %>
        <%= f.submit value: "dodaj" %>
    <% end %>
  </div>
</div>
<div class="loadingBox" style="display: none;" id="subcommentloadingbox_<%= comment.id %>">
  <span>trwa dodawanie komentarza</span>
  <div class="one"></div>
  <div class="two"></div>
  <div class="three"></div>
</div>
<% end %>

app/views/consultations/add_comment.html.erb
<p><%= @message %></p>

app/views/consultations/add_subcomment.html.erb
<%= @message %>

app/views/consultations/get_subcomments.html.erb
<section id="content">
  <div class="pagewidth">
    <article>
      <h1>Podkomentarze</h1>
      <% if @message %>
          <p><%= @message %></p>
      <% else %>
          <div id="comment">
          <div class="post">
            <img src="<%= @comment.user.image %>" class="avatar" alt="avatar" />
            <div class="content" id="comment_<%= @comment.id %>">
              <span><strong><%= @comment.user.name %></strong> - <%= time_ago_in_words(@comment.created_at) %> temu</span>
              <p><%= @comment.content %></p>
            </div>
            <%= render partial: 'subcomments_list', locals: { subcomments: @subcomments, comment: @comment } %>
          </div>
          </div>
      <% end %>
    </article>
  </div>
</section>

app/views/consultations/index.html.erb
<% content_for :title do %>
    Konsultacje Jastrzębie-Zdrój - platforma stworzona przez ludzi dla ludzi!
<% end %>

<section class="mainPage" id="about">
  <div class="pagewidth">
    <h2 class="">Zaproszenie Prezydenta Miasta Anny Hetman</h2>
    <h3><img src="<%= asset_path('index/prezydent.jpg') %>" alt="zdjecie prezydenta"/>Drodzy jastrzębianie,<br/>
      serwis konsultacyjny Urzędu Miasta Jastrzębia-Zdroju ma na celu bieżący dialog z mieszkańcami. Chcemy zapoznawać Państwa z planowanymi inwestycjami i projektami, ale przede wszystkim zachęcić do współdecydowaniu o losach miasta. Państwa zaangażowanie, szeroko pojęty dialog społeczny, któremu sprzyja wyrażanie własnej opinii, poglądów, dzielenie się swoimi uwagami i rozwiązaniami umożliwi nam poznanie Państwa stanowiska jeszcze na etapie planowania. To pozwoli na wybranie najlepszych rozwiązań i efektywne wprowadzenie ich w życie.
      Twórzmy razem nasze miasto!</h3>
  </div>
</section>
<section class="mainPage gray" id="content">
  <div class="pagewidth">
    <h2 class="">O serwisie</h2>
    <h3><iframe class="youtubeiframe" width="560" height="315" src="https://www.youtube.com/embed/JuOyECt65p0" frameborder="0" allowfullscreen></iframe>
      Celem tego serwisu jest promowanie dialogu społecznego, zwiększenie wiedzy i umiejętności mieszkańców w tym zakresie. Projekt ma zwrócić uwagę i uświadomić Jastrzębianom rolę aktywności społecznej w budowaniu społeczeństwa obywatelskiego, prowadzić do zmiany świadomości mieszkańców i pokazać, że mogą współdecydować o kształcie miasta, a co za tym idzie – jego i swojej przyszłości. Chcemy informować Państwa o inwestycjach realizowanych w mieście oraz zapoznać się z uwagami na ich temat. Tematy, co do których zbieramy opinie mieszkańców, pojawiać się będą  w postaci moderowanych wątków. Serwis jest administrowany przez pracowników Urzędu Miasta Jastrzębie-Zdrój. Przed rozpoczęciem korzystania z narzędzi dostępnych w ramach serwisu wymagane jest zapoznanie się z regulaminem. Zanim wyślesz swoją wiadomość przeczytaj ją dokładnie i sprawdź, czy odnosi się do konsultowanego tematu. Ułatwisz w ten sposób wyszukiwanie informacji innym użytkownikom. Należy pamiętać, że posty są dodawane po zaakceptowaniu przez moderatora danego wątku.<br/>
      UWAGA! Serwis konsultacyjny ma na celu poznanie opinii mieszkańców na różne tematy związane z życiem miasta. Do składania skarg i wniosków służy odrębna procedura (<a href="http://bip.jastrzebie.pl/contents/content/3970/24464">link</a>). </h3>
  </div>
</section>
<section class="mainPage">
  <div class="pagewidth">
    <h2 class="textCenter">Skontaktuj się z nami!</h2>
    <ul class="textCenter">
      <li>Urząd Miasta Jastrzębie-Zdrój</li>
      <li>al.J.Piłsudskiego 60</li>
      <li>44-335 Jastrzębie-Zdrój</li>
      <br/>
      <li><a href="mailto:konsultacje@um.jastrzebie.pl">konsultacje@um.jastrzebie.pl</a></li>
    </ul>
  </div>
</section>

app/views/consultations/list.html.erb
<% content_for :title do %>
    Konsultacje Jastrzębie-Zdrój - Lista konsultacji
<% end %>

<section id="content">
  <div class="pagewidth">
    <h2 class="textCenter"><%= @consultation_type %></h2>
    <div id="articleListMainPage">
      <% for consultation in @consultations %>
      <a href="<%= consultations_show_path(id: consultation.id) %>" class="articleBox two">
        <% unless consultation.consultation_type == 2 %>
            <span class="textCenter">Do końca pozostało: <%= distance_of_time_in_words(Time.now, consultation.end_date) %></span>
        <% end %>
        <h3 class="textCenter"><%= consultation.title %></h3>
        <div class="articleIconCloud"><%= consultation.consultation_comments.count %> komentarze</div>
      </a>
      <% end %>

    </div>
  </div>
</section>

app/views/consultations/show.html.erb
<% content_for :title do %>
    Konsultacje Jastrzębie-Zdrój - Konsultacja: <%= @consultation.title %>
<% end %>

<section id="content">
    <div class="pagewidth">
      <article>
        <h2><%= @consultation.title %><% if @consultation.consultation_type == 2%><span class="completedConsultationBox">zakończona</span><% end %></h2>
        <ul class="articleInfo">
          <% unless @consultation.consultation_type == 2 %>
              <li><div class="articleIcon clock"></div><span>Pozostało czasu: <%= distance_of_time_in_words(Time.now, @consultation.end_date) %></span></li>
          <% end %>
          <li><div class="articleIcon comment"></div><span>Ilość opinii:<span class="commentscount"><%= @consultation.consultation_comments.count %></span></span></li>
        </ul>
        <%= raw @consultation.content %>
        <% unless @consultation.formid.empty? %>
            <iframe src="https://docs.google.com/forms/d/<%= @consultation.formid %>/viewform?embedded=true" width="760" height="500" frameborder="0" marginheight="0" marginwidth="0">Ładowanie...</iframe>
        <% end %>
        <!--comments-->
        <div id="comment">
          <h4><span class="commentscount"><%= @consultation.consultation_comments.count %></span> opinie pod tą konsultacją</h4>
          <% if user_signed_in? %>
              <p id="loggedas">Zalogowano jako: <%= current_user.name %></p>

              <div id="mycomment" <% unless @oldc %>style="display: none;"<% end %>>
                <h4>Twój komentarz:</h4>
                  <div class="post">
                    <img src="<%= current_user.image.present? ? current_user.image : asset_path('post/avatar.jpg') %>" class="avatar" alt="avatar" />
                    <div class="content">
                      <span id="whoandago"><strong><%= current_user.name %></strong> - <%= time_ago_in_words(@oldc.created_at) if @oldc %> temu</span>
                      <p id="commenttext"><%= raw(h(@oldc.content).gsub(/\r/, '').gsub(/\n/, '<br>')) if @oldc %></p>
                      <a class="showReplyButton" id="gotocomment" onclick="$('#comment_<%= @oldc.id if @oldc %>').animatescroll();">przejdź do komentarza</a>
                    </div>
                  </div>
              </div>

              <% unless @oldc or @consultation.consultation_type == 2 %>
              <div class="post add" id="addmaincomment">
                <img src="<%= current_user.image.present? ? current_user.image : asset_path('post/avatar.jpg') %>" class="avatar" alt="avatar" />
                <div class="content">
                  <%= form_for :consultation_comment, remote: true, url: consultations_add_comment_path, html: { id: 'addmaincommentform'}, method: 'POST' do |f| %>
                      <input type="hidden" name="consultation_id" value="<%= @consultation.id %>" />
                      <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
                      <%= f.text_area :content, class: 'inputPost', placeholder: 'Podziel się swoją opinią', maxlength: 5000 %>
                    <%= f.submit value: "dodaj" %>
                  <% end %>
                </div>
              </div>

              <div class="loadingBox" style="display: none;" id="commentloadingbox">
                <span>trwa dodawanie opinii</span>
                <div class="one"></div>
                <div class="two"></div>
                <div class="three"></div>
              </div>
              <% end %>
          <% else %>
            <%= link_to "zaloguj się aby dodać opinię", new_user_session_path, class: 'signInFacebookButton' %>
          <% end %>

          <h4>Opinie</h4>
          <% for comment in @consultation.consultation_comments %>
            <%= render partial: 'comment', locals: {comment: comment} %>
          <% end %>
        </div>
      </article>
      <aside>
        <%= link_to "Więcej konsultacji", consultations_list_path(ctype: @consultation.consultation_type), class: "articleMoreButton" %>
        <% for consultation in @consultations %>
        <a href="<%= consultations_show_path(id: consultation.id) %>" class="articleBox post">
          <% unless @consultation.consultation_type == 2 %>
              <span class="textCenter">Do końca pozostało: <%= distance_of_time_in_words(Time.now, @consultation.end_date) %></span>
          <% end %>
          <h3 class="textCenter"><%= consultation.title %></h3>
          <div class="articleIconCloud"><%= consultation.consultation_comments.count %> komentarze</div>
        </a>
        <% end %>
      </aside>
    </div>
</section>

app/views/consultations/sitemap.html.erb
<% content_for :title do %>
    Konsultacje Jastrzębie-Zdrój - Lista konsultacji
<% end %>

<section class="siteMap" id="content">
  <div class="pagewidth">
    <h2>Mapa strony</h2>
    <article>
      <div class="main">
        <ul class="sitemap">
          <li><a href="<%= url_for root_path -%>">Strona główna</a></li>
          <li><a href="<%= url_for new_user_session_path -%>">Zaloguj się</a></li>
          <li><a href="<%= url_for new_user_registration_path -%>">Rejestracja</a></li>
          <li><a href="<%= url_for consultations_list_path -%>?ctype=0">Aktualne konsultacje</a></li>
          <li><a href="<%= url_for consultations_list_path -%>?ctype=1">Planowane konsultacje</a></li>
          <li><a href="<%= url_for consultations_list_path -%>?ctype=2">Zakończone konsultacje</a></li>
          <li><a href="<%= url_for consultations_sitemap_path -%>">Mapa strony</a></li>
          <li><a href="#">Regulamin</a></li>
        </ul>
      </div>
    </article>
  </div>

</section>