config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'consultations/index'
  get 'consultations/list'
  get 'consultations/show'
  post 'consultations/add_comment'
  post 'consultations/add_subcomment'
  get 'consultations/get_subcomments'
  get 'consultations/search'
  get 'consultations/report_post'
  get 'consultations/sitemap'

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks', registrations: 'registrations' }

   root 'consultations#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pl-PL" dir="ltr">
<head>
  <!-- Created by Media 3.0 -->
  <meta charset="utf-8" />
  <!--<meta name="viewport" content="width=device-width, initial-scale=1" />-->
  <meta name="viewport" content="width=1200" />
  <title><%= yield :title %></title>

  <meta name="author" content="Fundacja Media 3.0" />
  <meta name="description" content="To miejsce, gdzie możecie Państwo zapoznać się z projektami i opisami ważnych przedsięwzięć podejmowanych przez nasze miasto oraz podzielić się swoimi opiniami na ich temat." />
  <meta name="keywords" content="konsultacje społeczne, Jastrzębie-Zdrój" />
  <meta name="robots" content="index,follow" />

  <meta property="og:title" content="Konsultacje Jastrzębie-Zdrój - platforma stworzona przez ludzi dla ludzi!" />
  <meta property="og:type" content="website" />
  <meta property="og:image" content="http://konsultacje.jastrzebie.pl/logo.jpg" />
  <meta property="og:url" content="http://konsultacje.jastrzebie.pl/" />
  <meta property="og:site_name" content="Konsultacje Jastrzębie-Zdrój" />
  <meta property="og:description" content="To miejsce, gdzie możecie Państwo zapoznać się z projektami i opisami ważnych przedsięwzięć podejmowanych przez nasze miasto oraz podzielić się swoimi opiniami na ich temat." />
  <meta property="og:locale" content="pl_PL" />
  <meta property="fb:app_id" content="1386590734996335" />

  <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

  <link rel="shortcut icon" href="<%= asset_path('icon2.ico') %>" />

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

 
  <%= csrf_meta_tags %>
</head>
<body>
    <header <% if @index_page %>class="fullSize"<% end %>>
      <div class="pagewidth">
        <ul class="navwcag hiddenwcag">
          <li><a href="#topmenu" tabindex="4">Przejdź do menu</a></li>
          <li><a href="#content" tabindex="5">Przejdź do treści</a></li>
          <li><a href="/sitemap.html" tabindex="6">Mapa strony</a></li>
        </ul>
        <a id="logoJZ" href="http://www.jastrzebie.pl/"><%= image_tag 'header/logoJZ.png', alt: 'Oficjalny serwis miasta Jastrzębie-Zdrój' %></a>
        <h1><a id="logoKJZ" tabindex="1" href="<%= root_path %>"><%= image_tag 'header/logoKJZ.png', alt: 'Konsultacje Jastrzębie-Zdrój' %></a></h1>
        <div id="headerRight">
          <ul id="fontsTools">
            <li><a class="fontSizeMinus" title="Pomniejsz stronę">-A</a></li>
            <li><a class="fontReset" title="Przywróć podstawową wielkość strony">A</a></li>
            <li><a class="fontSizePlus" title="Powiększ stronę">+A</a></li>
            <li><a class="fontNContrast" href="javascript:HighContrastOff();" title="Domyślny kontrast strony">A</a></li>
            <li><a class="fontWBContrast" href="javascript:HighContrastOn();" title="Kontrast czarno-biały strony">A</a></li>
          </ul>
          <% unless user_signed_in? %>
              <%= link_to 'zaloguj', new_user_session_path, class: 'buttonHeader', id: 'signIn' %>
              <%= link_to 'rejestracja', new_user_registration_path, class: 'buttonHeader', id: 'register' %>
          <% else %>
              <%= link_to 'wyloguj', destroy_user_session_path, class: 'buttonHeader', id: 'signOut' %>
          <% end %>
          <form id="search" action="<%= url_for consultations_search_path %>" method="get">
            <label for="searchbox" class="hiddenwcag">Wyszukiwarka:</label>
            <input type="search" placeholder="szukaj..." tabindex="2" title="szukaj" name="q"/>
            <input type="submit" value=" " tabindex="3" title="Kliknij aby wyszukać"/>
          </form>
        </div>
        <nav>
          <ul>
            <li><%= nav_link 'Aktualne', consultations_list_path(ctype: 0), 'Aktualne konsultacje', 7 %></li>
            <li><%= nav_link 'Planowane', consultations_list_path(ctype: 1), 'Planowane konsultacje' %></li>
            <li><%= nav_link 'Zakończone', consultations_list_path(ctype: 2), 'Zakończone konsultacje' %></li>
          </ul>
        </nav>
        <% if @index_page %>
        <h2 class="textCenter">Platforma konsultacji społecznych</h2>
        <h3 class="textCenter">To miejsce, gdzie możecie Państwo zapoznać się z projektami i opisami ważnych przedsięwzięć podejmowanych przez nasze miasto oraz podzielić się swoimi opiniami na ich temat.</h3>
        <a class="headerMoreButton">Dowiedz się więcej</a>
        <% end %>
      </div>
    </header>

    <%= yield %>

    <footer>
      <div class="pagewidth">
        <div id="copyright">
          <p>Copyright © 2015 <a href="#"><strong>konsultacje.jastrzebie.pl</strong></a></p>
          <p>Created by <a href="http://media30.pl/"><strong>Media 3.0</strong></a></p>
        </div>
        <ul id="socialMedia">
          <li><a href="https://www.facebook.com/Miasto.Jastrzebie.Zdroj" class="socialMediaIcon facebook" title="Miasto Jastrzębie-Zdrój na Facebook'u"></a></li>
          <li><a href="https://www.youtube.com/user/MiastoJastrzebie" class="socialMediaIcon youtube" title="Miasto Jastrzębie-Zdrój na Youtube"></a></li>
        </ul>
        <ul id="footerNav">

          <li><%= link_to 'Mapa strony', consultations_sitemap_path -%></li>

          <% if user_signed_in? and current_user.admin? %>
              <li><%= link_to 'Panel Administracyjny', rails_admin_path %></li>
          <% end %>

          <% if user_signed_in? %>
              <li><%= link_to 'Wyloguj', destroy_user_session_path %></li>
          <% end %>

          <% unless user_signed_in? %>
              <li><%= link_to 'Zaloguj tradycyjnie', new_user_session_path %></li>
              <li><%= link_to 'Zaloguj przez facebook', user_omniauth_authorize_path(:facebook) %></li>
          <% end %>

          <li><a href="http://konsultacje.jastrzebie.pl/Regulamin_PKS.pdf" title="Regulamin PKS">Regulamin</a></li>
        </ul>
      </div>
    </footer>
<script>
    initializeEvents();
    initScriptsJs();
</script>
</body>
</html>